### ISSUE TITLE
Doesn't work with GHC 8.4.1

### ISSUE THREAD

**Issue by 23Skidoo** [jaspervdj/blaze-markup#37]
```
src/Text/Blaze/Internal.hs:222:25: error:
    • No instance for (Semigroup AttributeValue)
        arising from the 'deriving' clause of a data type declaration
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (Monoid AttributeValue)
    |
222 |     deriving (IsString, Monoid)
    |                         ^^^^^^
```

I suggest adding Hackage revisions changing the constraint on `base` to `>= 4 && < 4.11` in already-released versions.

**Comment by 23Skidoo** [comment]
Oh wait, seems to be fixed in `master`, I must have been using an old version.
